name: Checkstyle

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run docker
        run: docker compose up -d

      - name: gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Run check style
        uses: reviewdog/action-checkstyle@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_reporter: 'github-pr-review'
          checkstyle_tool_name: 'checkstyle'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: error
